query MinaBlockHeight {
  # @genqlient(typename: "MinaNetworkState")
  networkState {
    # @genqlient(typename: "MinaMaxBlockHeight")
    maxBlockHeight {
      pendingMaxBlockHeight
    }
  }
}

query MinaArchiveActions(
  $contractAddress: String!
  $from: Int!
  $to: Int!
  $blockHeightGte: Int!
  $blockHeightLt: Int!
  $blockLimit: Int!
) {
  # @genqlient(typename: "MinaAction")
  actions(
    input: {
      address: $contractAddress
      status: CANONICAL
      from: $from
      to: $to
    }
  ) {
    # @genqlient(typename: "MinaActionBlockInfo")
    blockInfo {
      height
    }

    # @genqlient(typename: "MinaActionData")
    actionData {
      data

      # @genqlient(typename: "MinaTransactionInfo")
      transactionInfo {
        hash
      }
    }
  }

  # @genqlient(typename: "MinaArchiveBlock")
  blocks(
    query: {
      blockHeight_gte: $blockHeightGte
      blockHeight_lt: $blockHeightLt
      canonical: true
      inBestChain: true
    }
    sortBy: BLOCKHEIGHT_ASC
    limit: $blockLimit
  ) {
    # @genqlient(typename: "MinaBlockTransactions")
    transactions {
      # @genqlient(typename: "MinaZkappCommand")
      zkappCommands {
        hash
        feePayer
      }
    }
  }
}