// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package fetchmina

import (
	"context"

	"github.com/Khan/genqlient/graphql"
)

// MinaAction includes the requested fields of the GraphQL type ArchiveActionGroup.
type MinaAction struct {
	BlockInfo  MinaActionBlockInfo `json:"blockInfo"`
	ActionData []MinaActionData    `json:"actionData"`
}

// GetBlockInfo returns MinaAction.BlockInfo, and is useful for accessing the field via an interface.
func (v *MinaAction) GetBlockInfo() MinaActionBlockInfo { return v.BlockInfo }

// GetActionData returns MinaAction.ActionData, and is useful for accessing the field via an interface.
func (v *MinaAction) GetActionData() []MinaActionData { return v.ActionData }

// MinaActionBlockInfo includes the requested fields of the GraphQL type ArchiveBlockInfo.
type MinaActionBlockInfo struct {
	Height int `json:"height"`
}

// GetHeight returns MinaActionBlockInfo.Height, and is useful for accessing the field via an interface.
func (v *MinaActionBlockInfo) GetHeight() int { return v.Height }

// MinaActionData includes the requested fields of the GraphQL type ArchiveActionData.
type MinaActionData struct {
	Data            []string            `json:"data"`
	TransactionInfo MinaTransactionInfo `json:"transactionInfo"`
}

// GetData returns MinaActionData.Data, and is useful for accessing the field via an interface.
func (v *MinaActionData) GetData() []string { return v.Data }

// GetTransactionInfo returns MinaActionData.TransactionInfo, and is useful for accessing the field via an interface.
func (v *MinaActionData) GetTransactionInfo() MinaTransactionInfo { return v.TransactionInfo }

// MinaArchiveActionsResponse is returned by MinaArchiveActions on success.
type MinaArchiveActionsResponse struct {
	Actions []MinaAction       `json:"actions"`
	Blocks  []MinaArchiveBlock `json:"blocks"`
}

// GetActions returns MinaArchiveActionsResponse.Actions, and is useful for accessing the field via an interface.
func (v *MinaArchiveActionsResponse) GetActions() []MinaAction { return v.Actions }

// GetBlocks returns MinaArchiveActionsResponse.Blocks, and is useful for accessing the field via an interface.
func (v *MinaArchiveActionsResponse) GetBlocks() []MinaArchiveBlock { return v.Blocks }

// MinaArchiveBlock includes the requested fields of the GraphQL type ArchiveBlock.
type MinaArchiveBlock struct {
	Transactions MinaBlockTransactions `json:"transactions"`
}

// GetTransactions returns MinaArchiveBlock.Transactions, and is useful for accessing the field via an interface.
func (v *MinaArchiveBlock) GetTransactions() MinaBlockTransactions { return v.Transactions }

// MinaBlockHeightResponse is returned by MinaBlockHeight on success.
type MinaBlockHeightResponse struct {
	NetworkState MinaNetworkState `json:"networkState"`
}

// GetNetworkState returns MinaBlockHeightResponse.NetworkState, and is useful for accessing the field via an interface.
func (v *MinaBlockHeightResponse) GetNetworkState() MinaNetworkState { return v.NetworkState }

// MinaBlockTransactions includes the requested fields of the GraphQL type ArchiveTransactions.
type MinaBlockTransactions struct {
	ZkappCommands []MinaZkappCommand `json:"zkappCommands"`
}

// GetZkappCommands returns MinaBlockTransactions.ZkappCommands, and is useful for accessing the field via an interface.
func (v *MinaBlockTransactions) GetZkappCommands() []MinaZkappCommand { return v.ZkappCommands }

// MinaMaxBlockHeight includes the requested fields of the GraphQL type MaxBlockHeight.
type MinaMaxBlockHeight struct {
	PendingMaxBlockHeight int `json:"pendingMaxBlockHeight"`
}

// GetPendingMaxBlockHeight returns MinaMaxBlockHeight.PendingMaxBlockHeight, and is useful for accessing the field via an interface.
func (v *MinaMaxBlockHeight) GetPendingMaxBlockHeight() int { return v.PendingMaxBlockHeight }

// MinaNetworkState includes the requested fields of the GraphQL type NetworkState.
type MinaNetworkState struct {
	MaxBlockHeight MinaMaxBlockHeight `json:"maxBlockHeight"`
}

// GetMaxBlockHeight returns MinaNetworkState.MaxBlockHeight, and is useful for accessing the field via an interface.
func (v *MinaNetworkState) GetMaxBlockHeight() MinaMaxBlockHeight { return v.MaxBlockHeight }

// MinaTransactionInfo includes the requested fields of the GraphQL type ArchiveTransactionInfo.
type MinaTransactionInfo struct {
	Hash string `json:"hash"`
}

// GetHash returns MinaTransactionInfo.Hash, and is useful for accessing the field via an interface.
func (v *MinaTransactionInfo) GetHash() string { return v.Hash }

// MinaZkappCommand includes the requested fields of the GraphQL type ArchiveZkappCommand.
type MinaZkappCommand struct {
	Hash     string `json:"hash"`
	FeePayer string `json:"feePayer"`
}

// GetHash returns MinaZkappCommand.Hash, and is useful for accessing the field via an interface.
func (v *MinaZkappCommand) GetHash() string { return v.Hash }

// GetFeePayer returns MinaZkappCommand.FeePayer, and is useful for accessing the field via an interface.
func (v *MinaZkappCommand) GetFeePayer() string { return v.FeePayer }

// __MinaArchiveActionsInput is used internally by genqlient
type __MinaArchiveActionsInput struct {
	ContractAddress string `json:"contractAddress"`
	From            int    `json:"from"`
	To              int    `json:"to"`
	BlockHeightGte  int    `json:"blockHeightGte"`
	BlockHeightLt   int    `json:"blockHeightLt"`
	BlockLimit      int    `json:"blockLimit"`
}

// GetContractAddress returns __MinaArchiveActionsInput.ContractAddress, and is useful for accessing the field via an interface.
func (v *__MinaArchiveActionsInput) GetContractAddress() string { return v.ContractAddress }

// GetFrom returns __MinaArchiveActionsInput.From, and is useful for accessing the field via an interface.
func (v *__MinaArchiveActionsInput) GetFrom() int { return v.From }

// GetTo returns __MinaArchiveActionsInput.To, and is useful for accessing the field via an interface.
func (v *__MinaArchiveActionsInput) GetTo() int { return v.To }

// GetBlockHeightGte returns __MinaArchiveActionsInput.BlockHeightGte, and is useful for accessing the field via an interface.
func (v *__MinaArchiveActionsInput) GetBlockHeightGte() int { return v.BlockHeightGte }

// GetBlockHeightLt returns __MinaArchiveActionsInput.BlockHeightLt, and is useful for accessing the field via an interface.
func (v *__MinaArchiveActionsInput) GetBlockHeightLt() int { return v.BlockHeightLt }

// GetBlockLimit returns __MinaArchiveActionsInput.BlockLimit, and is useful for accessing the field via an interface.
func (v *__MinaArchiveActionsInput) GetBlockLimit() int { return v.BlockLimit }

// The query executed by MinaArchiveActions.
const MinaArchiveActions_Operation = `
query MinaArchiveActions ($contractAddress: String!, $from: Int!, $to: Int!, $blockHeightGte: Int!, $blockHeightLt: Int!, $blockLimit: Int!) {
	actions(input: {address:$contractAddress,status:CANONICAL,from:$from,to:$to}) {
		blockInfo {
			height
		}
		actionData {
			data
			transactionInfo {
				hash
			}
		}
	}
	blocks(query: {blockHeight_gte:$blockHeightGte,blockHeight_lt:$blockHeightLt,canonical:true,inBestChain:true}, sortBy: BLOCKHEIGHT_ASC, limit: $blockLimit) {
		transactions {
			zkappCommands {
				hash
				feePayer
			}
		}
	}
}
`

func MinaArchiveActions(
	ctx_ context.Context,
	client_ graphql.Client,
	contractAddress string,
	from int,
	to int,
	blockHeightGte int,
	blockHeightLt int,
	blockLimit int,
) (data_ *MinaArchiveActionsResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "MinaArchiveActions",
		Query:  MinaArchiveActions_Operation,
		Variables: &__MinaArchiveActionsInput{
			ContractAddress: contractAddress,
			From:            from,
			To:              to,
			BlockHeightGte:  blockHeightGte,
			BlockHeightLt:   blockHeightLt,
			BlockLimit:      blockLimit,
		},
	}

	data_ = &MinaArchiveActionsResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by MinaBlockHeight.
const MinaBlockHeight_Operation = `
query MinaBlockHeight {
	networkState {
		maxBlockHeight {
			pendingMaxBlockHeight
		}
	}
}
`

func MinaBlockHeight(
	ctx_ context.Context,
	client_ graphql.Client,
) (data_ *MinaBlockHeightResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "MinaBlockHeight",
		Query:  MinaBlockHeight_Operation,
	}

	data_ = &MinaBlockHeightResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}
