schema {
  query: Query
}

type Query {
  networkState: NetworkState!
  actions(input: ActionFilterOptionsInput!): [ArchiveActionGroup!]!
  blocks(query: BlockQueryInput, sortBy: BlockSortBy, limit: Int): [ArchiveBlock!]!
}

type NetworkState {
  maxBlockHeight: MaxBlockHeight!
}

type MaxBlockHeight {
  pendingMaxBlockHeight: Int!
}

input ActionFilterOptionsInput {
  address: String!
  status: ActionStatus
  from: Int!
  to: Int!
}

enum ActionStatus {
  CANONICAL
}

type ArchiveActionGroup {
  blockInfo: ArchiveBlockInfo!
  actionData: [ArchiveActionData!]!
}

type ArchiveBlockInfo {
  height: Int!
}

type ArchiveActionData {
  data: [String!]!
  transactionInfo: ArchiveTransactionInfo!
}

type ArchiveTransactionInfo {
  hash: String!
}

input BlockQueryInput {
  blockHeight_gte: Int
  blockHeight_lt: Int
  canonical: Boolean
  inBestChain: Boolean
}

enum BlockSortBy {
  BLOCKHEIGHT_ASC
}

type ArchiveBlock {
  transactions: ArchiveTransactions!
}

type ArchiveTransactions {
  zkappCommands: [ArchiveZkappCommand!]!
}

type ArchiveZkappCommand {
  hash: String!
  feePayer: String!
}