// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AccountIdentifier struct {
	ID          int64
	PublicKeyID int64
}

type Block struct {
	ID                     int64
	Height                 int64
	ChainStatus            string
	GlobalSlotSinceGenesis pgtype.Int8
	ParentID               pgtype.Int8
	ParentHash             pgtype.Text
	StateHash              pgtype.Text
}

type BlocksZkappCommand struct {
	BlockID        int64
	ZkappCommandID int64
	SequenceNo     int64
}

type PublicKey struct {
	ID    int64
	Value string
}

type ZkappAccountUpdate struct {
	ID     int64
	BodyID int64
}

type ZkappAccountUpdateBody struct {
	ID                  int64
	AccountIdentifierID int64
	ActionsID           int64
}

type ZkappCommand struct {
	ID                     int64
	ZkappFeePayerBodyID    int64
	ZkappAccountUpdatesIds []int64
	Hash                   string
}

type ZkappEvent struct {
	ID         int64
	ElementIds []int64
}

type ZkappFeePayerBody struct {
	ID          int64
	PublicKeyID int64
}

type ZkappField struct {
	ID    int64
	Field string
}

type ZkappFieldArray struct {
	ID         int64
	ElementIds []int64
}
