// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type AccountIdentifier struct {
	ID          int64
	PublicKeyID int64
}

type Block struct {
	ID          int64
	Height      int64
	ChainStatus string
}

type BlocksZkappCommand struct {
	BlockID        int64
	ZkappCommandID int64
	SequenceNo     int64
}

type PublicKey struct {
	ID    int64
	Value string
}

type ZkappAccountUpdate struct {
	ID     int64
	BodyID int64
}

type ZkappAccountUpdateBody struct {
	ID                  int64
	AccountIdentifierID int64
	ActionsID           int64
}

type ZkappCommand struct {
	ID                     int64
	ZkappFeePayerBodyID    int64
	ZkappAccountUpdatesIds []int64
	Hash                   string
}

type ZkappEvent struct {
	ID         int64
	ElementIds []int64
}

type ZkappFeePayerBody struct {
	ID          int64
	PublicKeyID int64
}

type ZkappField struct {
	ID    int64
	Field string
}

type ZkappFieldArray struct {
	ID         int64
	ElementIds []int64
}
