// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	GetLatestBlockHeight(ctx context.Context) (int64, error)
	ListActionRows(ctx context.Context, arg ListActionRowsParams) ([]ListActionRowsRow, error)
}

var _ Querier = (*Queries)(nil)
