// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
)

const getLatestBlockHeight = `-- name: GetLatestBlockHeight :one
SELECT COALESCE(MAX(height), 0)::bigint
FROM blocks
WHERE chain_status = 'pending'
`

func (q *Queries) GetLatestBlockHeight(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getLatestBlockHeight)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const listActionRows = `-- name: ListActionRows :many
WITH RECURSIVE
pending_tip AS (
  SELECT
    b.id,
    b.parent_id,
    b.height::bigint AS height
  FROM blocks b
  WHERE b.chain_status = 'pending'
    AND NOT EXISTS (
      SELECT 1
      FROM blocks child
      WHERE child.parent_id = b.id
        AND child.chain_status = 'pending'
    )
  ORDER BY
    b.height DESC,
    COALESCE(b.global_slot_since_genesis, 0) DESC,
    b.id DESC
  LIMIT 1
),
best_chain AS (
  SELECT id, parent_id, height
  FROM pending_tip

  UNION ALL

  SELECT b.id, b.parent_id, b.height::bigint
  FROM blocks b
  JOIN best_chain bc ON bc.parent_id = b.id
),
action_rows AS (
  SELECT
    b.id AS block_id,
    b.height::bigint AS height,
    bzc.sequence_no,
    action_array.action_index,
    zau.id AS account_update_id,
    zc.id AS zkapp_command_id,
    zc.hash,
    fee_pk.value AS fee_payer,
    COALESCE(
      array_agg(field.field ORDER BY action_field.field_index)
        FILTER (WHERE field.field IS NOT NULL),
      ARRAY[]::text[]
    )::text[] AS data
  FROM best_chain bc
  JOIN blocks b ON b.id = bc.id
  JOIN blocks_zkapp_commands bzc ON bzc.block_id = b.id
  JOIN zkapp_commands zc ON zc.id = bzc.zkapp_command_id
  JOIN zkapp_fee_payer_body zfpb ON zfpb.id = zc.zkapp_fee_payer_body_id
  JOIN public_keys fee_pk ON fee_pk.id = zfpb.public_key_id
  JOIN LATERAL unnest(zc.zkapp_account_updates_ids)
    WITH ORDINALITY AS command_update(account_update_id, account_update_index) ON true
  JOIN zkapp_account_update zau ON zau.id = command_update.account_update_id
  JOIN zkapp_account_update_body zaub ON zaub.id = zau.body_id
  JOIN account_identifiers ai ON ai.id = zaub.account_identifier_id
  JOIN public_keys account_pk ON account_pk.id = ai.public_key_id
  JOIN zkapp_events actions ON actions.id = zaub.actions_id
  JOIN LATERAL unnest(actions.element_ids)
    WITH ORDINALITY AS action_array(field_array_id, action_index) ON true
  JOIN zkapp_field_array field_array ON field_array.id = action_array.field_array_id
  LEFT JOIN LATERAL unnest(field_array.element_ids)
    WITH ORDINALITY AS action_field(field_id, field_index) ON true
  LEFT JOIN zkapp_field field ON field.id = action_field.field_id
  WHERE account_pk.value = $1::text
    AND b.height = $2::bigint
  GROUP BY
    b.id,
    b.height,
    bzc.sequence_no,
    action_array.action_index,
    zau.id,
    zc.id,
    zc.hash,
    fee_pk.value
),
deduped_action_rows AS (
  SELECT DISTINCT ON (zkapp_command_id, account_update_id, action_index)
    height,
    fee_payer,
    data
  FROM action_rows
  ORDER BY
    zkapp_command_id,
    account_update_id,
    action_index,
    block_id DESC,
    sequence_no DESC
)
SELECT height, fee_payer, data
FROM deduped_action_rows
ORDER BY height, fee_payer
`

type ListActionRowsParams struct {
	ContractAddress string
	Height          int64
}

type ListActionRowsRow struct {
	Height   int64
	FeePayer string
	Data     []string
}

func (q *Queries) ListActionRows(ctx context.Context, arg ListActionRowsParams) ([]ListActionRowsRow, error) {
	rows, err := q.db.Query(ctx, listActionRows, arg.ContractAddress, arg.Height)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActionRowsRow{}
	for rows.Next() {
		var i ListActionRowsRow
		if err := rows.Scan(&i.Height, &i.FeePayer, &i.Data); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
