// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	GetBestChainBlockIDAtHeight(ctx context.Context, height int64) (GetBestChainBlockIDAtHeightRow, error)
	GetLatestBlockHeight(ctx context.Context) (int64, error)
	ListActionRowsByBlockID(ctx context.Context, arg ListActionRowsByBlockIDParams) ([]ListActionRowsByBlockIDRow, error)
	ListBestChainBlockIDsInRange(ctx context.Context, arg ListBestChainBlockIDsInRangeParams) ([]ListBestChainBlockIDsInRangeRow, error)
}

var _ Querier = (*Queries)(nil)
