// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: query/query.proto

package query

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	actions "github.com/node101-io/archive-wrapper/actions"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryGetActionsInRangeRequest struct {
	// Inclusive block-height range. The maximum supported width is configured by
	// the current bridge max block range.
	StartBlockHeight int64 `protobuf:"varint,1,opt,name=start_block_height,json=startBlockHeight,proto3" json:"start_block_height,omitempty"`
	EndBlockHeight   int64 `protobuf:"varint,2,opt,name=end_block_height,json=endBlockHeight,proto3" json:"end_block_height,omitempty"`
}

func (m *QueryGetActionsInRangeRequest) Reset()         { *m = QueryGetActionsInRangeRequest{} }
func (m *QueryGetActionsInRangeRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetActionsInRangeRequest) ProtoMessage()    {}
func (*QueryGetActionsInRangeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf5d1f792f5992be, []int{0}
}
func (m *QueryGetActionsInRangeRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetActionsInRangeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetActionsInRangeRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetActionsInRangeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetActionsInRangeRequest.Merge(m, src)
}
func (m *QueryGetActionsInRangeRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetActionsInRangeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetActionsInRangeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetActionsInRangeRequest proto.InternalMessageInfo

type QueryGetActionsInRangeResponse struct {
	Actions []*actions.Action `protobuf:"bytes,1,rep,name=actions,proto3" json:"actions,omitempty"`
}

func (m *QueryGetActionsInRangeResponse) Reset()         { *m = QueryGetActionsInRangeResponse{} }
func (m *QueryGetActionsInRangeResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetActionsInRangeResponse) ProtoMessage()    {}
func (*QueryGetActionsInRangeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf5d1f792f5992be, []int{1}
}
func (m *QueryGetActionsInRangeResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetActionsInRangeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetActionsInRangeResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetActionsInRangeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetActionsInRangeResponse.Merge(m, src)
}
func (m *QueryGetActionsInRangeResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetActionsInRangeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetActionsInRangeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetActionsInRangeResponse proto.InternalMessageInfo

type QueryGetMinaBlockHeightRequest struct {
}

func (m *QueryGetMinaBlockHeightRequest) Reset()         { *m = QueryGetMinaBlockHeightRequest{} }
func (m *QueryGetMinaBlockHeightRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetMinaBlockHeightRequest) ProtoMessage()    {}
func (*QueryGetMinaBlockHeightRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf5d1f792f5992be, []int{2}
}
func (m *QueryGetMinaBlockHeightRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetMinaBlockHeightRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetMinaBlockHeightRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetMinaBlockHeightRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetMinaBlockHeightRequest.Merge(m, src)
}
func (m *QueryGetMinaBlockHeightRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetMinaBlockHeightRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetMinaBlockHeightRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetMinaBlockHeightRequest proto.InternalMessageInfo

type QueryGetMinaBlockHeightResponse struct {
	BlockHeight int64 `protobuf:"varint,1,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
}

func (m *QueryGetMinaBlockHeightResponse) Reset()         { *m = QueryGetMinaBlockHeightResponse{} }
func (m *QueryGetMinaBlockHeightResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetMinaBlockHeightResponse) ProtoMessage()    {}
func (*QueryGetMinaBlockHeightResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf5d1f792f5992be, []int{3}
}
func (m *QueryGetMinaBlockHeightResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetMinaBlockHeightResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetMinaBlockHeightResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetMinaBlockHeightResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetMinaBlockHeightResponse.Merge(m, src)
}
func (m *QueryGetMinaBlockHeightResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetMinaBlockHeightResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetMinaBlockHeightResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetMinaBlockHeightResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*QueryGetActionsInRangeRequest)(nil), "query.QueryGetActionsInRangeRequest")
	proto.RegisterType((*QueryGetActionsInRangeResponse)(nil), "query.QueryGetActionsInRangeResponse")
	proto.RegisterType((*QueryGetMinaBlockHeightRequest)(nil), "query.QueryGetMinaBlockHeightRequest")
	proto.RegisterType((*QueryGetMinaBlockHeightResponse)(nil), "query.QueryGetMinaBlockHeightResponse")
}

func init() { proto.RegisterFile("query/query.proto", fileDescriptor_bf5d1f792f5992be) }

var fileDescriptor_bf5d1f792f5992be = []byte{
	// 349 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0x2c, 0x4d, 0x2d,
	0xaa, 0xd4, 0x07, 0x93, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0xac, 0x60, 0x8e, 0x94, 0x48,
	0x62, 0x72, 0x49, 0x66, 0x7e, 0x5e, 0xb1, 0x3e, 0x84, 0x86, 0x48, 0x4a, 0x89, 0xa4, 0xe7, 0xa7,
	0xe7, 0x83, 0x99, 0xfa, 0x20, 0x16, 0x44, 0x54, 0xa9, 0x96, 0x4b, 0x36, 0x10, 0xa4, 0xc9, 0x3d,
	0xb5, 0xc4, 0x11, 0xa2, 0xcb, 0x33, 0x2f, 0x28, 0x31, 0x2f, 0x3d, 0x35, 0x28, 0xb5, 0xb0, 0x34,
	0xb5, 0xb8, 0x44, 0x48, 0x87, 0x4b, 0xa8, 0xb8, 0x24, 0xb1, 0xa8, 0x24, 0x3e, 0x29, 0x27, 0x3f,
	0x39, 0x3b, 0x3e, 0x23, 0x35, 0x33, 0x3d, 0xa3, 0x44, 0x82, 0x51, 0x81, 0x51, 0x83, 0x39, 0x48,
	0x00, 0x2c, 0xe3, 0x04, 0x92, 0xf0, 0x00, 0x8b, 0x0b, 0x69, 0x70, 0x09, 0xa4, 0xe6, 0xa5, 0xa0,
	0xaa, 0x65, 0x02, 0xab, 0xe5, 0x4b, 0xcd, 0x4b, 0x41, 0x52, 0x69, 0xc5, 0xd2, 0xb1, 0x40, 0x9e,
	0x41, 0x29, 0x90, 0x4b, 0x0e, 0x97, 0xf5, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x42, 0x9a, 0x5c,
	0xec, 0x50, 0xef, 0x48, 0x30, 0x2a, 0x30, 0x6b, 0x70, 0x1b, 0xf1, 0xeb, 0x41, 0xf9, 0x7a, 0x10,
	0x1d, 0x41, 0x30, 0x79, 0xa8, 0x91, 0x6a, 0x08, 0x23, 0x7d, 0x33, 0xf3, 0x12, 0x91, 0xec, 0x84,
	0x7a, 0x09, 0xaa, 0xce, 0x8b, 0x4b, 0x1e, 0xa7, 0x3a, 0xa8, 0xdd, 0x8a, 0x5c, 0x3c, 0x58, 0x7c,
	0xcd, 0x9d, 0x84, 0xee, 0x0d, 0xa3, 0x73, 0x8c, 0x5c, 0xac, 0x60, 0xc3, 0x84, 0x12, 0xb8, 0x04,
	0x31, 0xfc, 0x22, 0xa4, 0xa2, 0x07, 0x89, 0x25, 0xbc, 0x21, 0x2d, 0xa5, 0x4a, 0x40, 0x15, 0xd4,
	0x51, 0xc9, 0x5c, 0x42, 0x98, 0x4e, 0x16, 0x42, 0xd7, 0x8c, 0xdd, 0xeb, 0x52, 0x6a, 0x84, 0x94,
	0x41, 0x2c, 0x71, 0xf2, 0x3e, 0xf1, 0x48, 0x8e, 0xf1, 0xc2, 0x23, 0x39, 0xc6, 0x07, 0x8f, 0xe4,
	0x18, 0x27, 0x3c, 0x96, 0x63, 0xb8, 0xf0, 0x58, 0x8e, 0xe1, 0xc6, 0x63, 0x39, 0x86, 0x28, 0xc3,
	0xf4, 0xcc, 0x92, 0x8c, 0xd2, 0x24, 0xbd, 0xe4, 0xfc, 0x5c, 0xfd, 0xbc, 0xfc, 0x94, 0x54, 0x43,
	0x03, 0x43, 0xdd, 0xcc, 0x7c, 0xfd, 0xc4, 0xa2, 0xe4, 0x8c, 0xcc, 0xb2, 0x54, 0xdd, 0xf2, 0xa2,
	0xc4, 0x82, 0x82, 0xd4, 0x22, 0x48, 0xb2, 0xb4, 0x06, 0x93, 0x49, 0x6c, 0xe0, 0xa4, 0x66, 0x0c,
	0x08, 0x00, 0x00, 0xff, 0xff, 0x84, 0x0f, 0xba, 0x95, 0xb2, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// GetActionsInRange returns actions for an inclusive indexed block range.
	// Requests wider than the configured max block range are rejected.
	GetActionsInRange(ctx context.Context, in *QueryGetActionsInRangeRequest, opts ...grpc.CallOption) (*QueryGetActionsInRangeResponse, error)
	GetMinaBlockHeight(ctx context.Context, in *QueryGetMinaBlockHeightRequest, opts ...grpc.CallOption) (*QueryGetMinaBlockHeightResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) GetActionsInRange(ctx context.Context, in *QueryGetActionsInRangeRequest, opts ...grpc.CallOption) (*QueryGetActionsInRangeResponse, error) {
	out := new(QueryGetActionsInRangeResponse)
	err := c.cc.Invoke(ctx, "/query.Query/GetActionsInRange", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetMinaBlockHeight(ctx context.Context, in *QueryGetMinaBlockHeightRequest, opts ...grpc.CallOption) (*QueryGetMinaBlockHeightResponse, error) {
	out := new(QueryGetMinaBlockHeightResponse)
	err := c.cc.Invoke(ctx, "/query.Query/GetMinaBlockHeight", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// GetActionsInRange returns actions for an inclusive indexed block range.
	// Requests wider than the configured max block range are rejected.
	GetActionsInRange(context.Context, *QueryGetActionsInRangeRequest) (*QueryGetActionsInRangeResponse, error)
	GetMinaBlockHeight(context.Context, *QueryGetMinaBlockHeightRequest) (*QueryGetMinaBlockHeightResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) GetActionsInRange(ctx context.Context, req *QueryGetActionsInRangeRequest) (*QueryGetActionsInRangeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetActionsInRange not implemented")
}
func (*UnimplementedQueryServer) GetMinaBlockHeight(ctx context.Context, req *QueryGetMinaBlockHeightRequest) (*QueryGetMinaBlockHeightResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMinaBlockHeight not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_GetActionsInRange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetActionsInRangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetActionsInRange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/query.Query/GetActionsInRange",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetActionsInRange(ctx, req.(*QueryGetActionsInRangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetMinaBlockHeight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetMinaBlockHeightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetMinaBlockHeight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/query.Query/GetMinaBlockHeight",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetMinaBlockHeight(ctx, req.(*QueryGetMinaBlockHeightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "query.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetActionsInRange",
			Handler:    _Query_GetActionsInRange_Handler,
		},
		{
			MethodName: "GetMinaBlockHeight",
			Handler:    _Query_GetMinaBlockHeight_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "query/query.proto",
}

func (m *QueryGetActionsInRangeRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetActionsInRangeRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetActionsInRangeRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.EndBlockHeight != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.EndBlockHeight))
		i--
		dAtA[i] = 0x10
	}
	if m.StartBlockHeight != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.StartBlockHeight))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetActionsInRangeResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetActionsInRangeResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetActionsInRangeResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Actions) > 0 {
		for iNdEx := len(m.Actions) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Actions[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetMinaBlockHeightRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetMinaBlockHeightRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetMinaBlockHeightRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryGetMinaBlockHeightResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetMinaBlockHeightResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetMinaBlockHeightResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.BlockHeight != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.BlockHeight))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryGetActionsInRangeRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.StartBlockHeight != 0 {
		n += 1 + sovQuery(uint64(m.StartBlockHeight))
	}
	if m.EndBlockHeight != 0 {
		n += 1 + sovQuery(uint64(m.EndBlockHeight))
	}
	return n
}

func (m *QueryGetActionsInRangeResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Actions) > 0 {
		for _, e := range m.Actions {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryGetMinaBlockHeightRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryGetMinaBlockHeightResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BlockHeight != 0 {
		n += 1 + sovQuery(uint64(m.BlockHeight))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryGetActionsInRangeRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetActionsInRangeRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetActionsInRangeRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartBlockHeight", wireType)
			}
			m.StartBlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StartBlockHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndBlockHeight", wireType)
			}
			m.EndBlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EndBlockHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetActionsInRangeResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetActionsInRangeResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetActionsInRangeResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Actions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Actions = append(m.Actions, &actions.Action{})
			if err := m.Actions[len(m.Actions)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetMinaBlockHeightRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetMinaBlockHeightRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetMinaBlockHeightRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetMinaBlockHeightResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetMinaBlockHeightResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetMinaBlockHeightResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHeight", wireType)
			}
			m.BlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
