syntax = "proto3";

package query;

import "actions/action.proto";
import "gogoproto/gogo.proto";

option go_package = "github.com/node101-io/archive-wrapper/query;query";

service Query {
  rpc ActionsByBlockHeight(QueryActionsByBlockHeightRequest) returns (QueryActionsByBlockHeightResponse);
}

message QueryActionsByBlockHeightRequest {
  option (gogoproto.goproto_getters) = false;

  int64 block_height = 1;
}

message QueryActionsByBlockHeightResponse {
  option (gogoproto.goproto_getters) = false;

  repeated actions.Action actions = 1;
}