// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: diagnostics/diagnostics.proto

package diagnostics

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type OperationalState int32

const (
	OperationalState_OPERATIONAL_STATE_UNSPECIFIED          OperationalState = 0
	OperationalState_OPERATIONAL_STATE_STARTING             OperationalState = 1
	OperationalState_OPERATIONAL_STATE_CONNECTING           OperationalState = 2
	OperationalState_OPERATIONAL_STATE_SYNCING              OperationalState = 3
	OperationalState_OPERATIONAL_STATE_WAITING_FOR_FINALITY OperationalState = 4
	OperationalState_OPERATIONAL_STATE_READY                OperationalState = 5
	OperationalState_OPERATIONAL_STATE_RECONNECTING         OperationalState = 6
	OperationalState_OPERATIONAL_STATE_FAILED               OperationalState = 7
	OperationalState_OPERATIONAL_STATE_STOPPING             OperationalState = 8
)

var OperationalState_name = map[int32]string{
	0: "OPERATIONAL_STATE_UNSPECIFIED",
	1: "OPERATIONAL_STATE_STARTING",
	2: "OPERATIONAL_STATE_CONNECTING",
	3: "OPERATIONAL_STATE_SYNCING",
	4: "OPERATIONAL_STATE_WAITING_FOR_FINALITY",
	5: "OPERATIONAL_STATE_READY",
	6: "OPERATIONAL_STATE_RECONNECTING",
	7: "OPERATIONAL_STATE_FAILED",
	8: "OPERATIONAL_STATE_STOPPING",
}

var OperationalState_value = map[string]int32{
	"OPERATIONAL_STATE_UNSPECIFIED":          0,
	"OPERATIONAL_STATE_STARTING":             1,
	"OPERATIONAL_STATE_CONNECTING":           2,
	"OPERATIONAL_STATE_SYNCING":              3,
	"OPERATIONAL_STATE_WAITING_FOR_FINALITY": 4,
	"OPERATIONAL_STATE_READY":                5,
	"OPERATIONAL_STATE_RECONNECTING":         6,
	"OPERATIONAL_STATE_FAILED":               7,
	"OPERATIONAL_STATE_STOPPING":             8,
}

func (x OperationalState) String() string {
	return proto.EnumName(OperationalState_name, int32(x))
}

func (OperationalState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1418b64243aec797, []int{0}
}

type GetStatusRequest struct {
}

func (m *GetStatusRequest) Reset()         { *m = GetStatusRequest{} }
func (m *GetStatusRequest) String() string { return proto.CompactTextString(m) }
func (*GetStatusRequest) ProtoMessage()    {}
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1418b64243aec797, []int{0}
}
func (m *GetStatusRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetStatusRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStatusRequest.Merge(m, src)
}
func (m *GetStatusRequest) XXX_Size() int {
	return m.Size()
}
func (m *GetStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetStatusRequest proto.InternalMessageInfo

type GetStatusResponse struct {
	State                OperationalState `protobuf:"varint,1,opt,name=state,proto3,enum=diagnostics.OperationalState" json:"state,omitempty"`
	Ready                bool             `protobuf:"varint,2,opt,name=ready,proto3" json:"ready,omitempty"`
	Indexer              IndexerStatus    `protobuf:"bytes,3,opt,name=indexer,proto3" json:"indexer"`
	StateSince           *time.Time       `protobuf:"bytes,4,opt,name=state_since,json=stateSince,proto3,stdtime" json:"state_since,omitempty"`
	LastSuccessfulSyncAt *time.Time       `protobuf:"bytes,5,opt,name=last_successful_sync_at,json=lastSuccessfulSyncAt,proto3,stdtime" json:"last_successful_sync_at,omitempty"`
	LastErrorAt          *time.Time       `protobuf:"bytes,6,opt,name=last_error_at,json=lastErrorAt,proto3,stdtime" json:"last_error_at,omitempty"`
	LastError            string           `protobuf:"bytes,7,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
}

func (m *GetStatusResponse) Reset()         { *m = GetStatusResponse{} }
func (m *GetStatusResponse) String() string { return proto.CompactTextString(m) }
func (*GetStatusResponse) ProtoMessage()    {}
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1418b64243aec797, []int{1}
}
func (m *GetStatusResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetStatusResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStatusResponse.Merge(m, src)
}
func (m *GetStatusResponse) XXX_Size() int {
	return m.Size()
}
func (m *GetStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetStatusResponse proto.InternalMessageInfo

type IndexerStatus struct {
	Initialized   bool  `protobuf:"varint,1,opt,name=initialized,proto3" json:"initialized,omitempty"`
	IndexedHeight int64 `protobuf:"varint,2,opt,name=indexed_height,json=indexedHeight,proto3" json:"indexed_height,omitempty"`
	ArchiveHeight int64 `protobuf:"varint,3,opt,name=archive_height,json=archiveHeight,proto3" json:"archive_height,omitempty"`
	TargetHeight  int64 `protobuf:"varint,4,opt,name=target_height,json=targetHeight,proto3" json:"target_height,omitempty"`
	ConfirmedLag  int64 `protobuf:"varint,5,opt,name=confirmed_lag,json=confirmedLag,proto3" json:"confirmed_lag,omitempty"`
}

func (m *IndexerStatus) Reset()         { *m = IndexerStatus{} }
func (m *IndexerStatus) String() string { return proto.CompactTextString(m) }
func (*IndexerStatus) ProtoMessage()    {}
func (*IndexerStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_1418b64243aec797, []int{2}
}
func (m *IndexerStatus) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *IndexerStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_IndexerStatus.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *IndexerStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexerStatus.Merge(m, src)
}
func (m *IndexerStatus) XXX_Size() int {
	return m.Size()
}
func (m *IndexerStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexerStatus.DiscardUnknown(m)
}

var xxx_messageInfo_IndexerStatus proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("diagnostics.OperationalState", OperationalState_name, OperationalState_value)
	proto.RegisterType((*GetStatusRequest)(nil), "diagnostics.GetStatusRequest")
	proto.RegisterType((*GetStatusResponse)(nil), "diagnostics.GetStatusResponse")
	proto.RegisterType((*IndexerStatus)(nil), "diagnostics.IndexerStatus")
}

func init() { proto.RegisterFile("diagnostics/diagnostics.proto", fileDescriptor_1418b64243aec797) }

var fileDescriptor_1418b64243aec797 = []byte{
	// 677 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0xcf, 0x4e, 0xdb, 0x4c,
	0x14, 0xc5, 0x63, 0x92, 0xf0, 0xe7, 0x86, 0xa0, 0x7c, 0x23, 0x24, 0xfc, 0xa5, 0xc4, 0x49, 0xa9,
	0x5a, 0x45, 0x48, 0x24, 0x05, 0x76, 0x54, 0x5d, 0x98, 0xc4, 0xa1, 0xae, 0xa2, 0x24, 0xb2, 0x53,
	0x21, 0xba, 0x71, 0x07, 0x7b, 0x70, 0x46, 0x4a, 0x3c, 0xa9, 0x67, 0x42, 0x4b, 0x9f, 0xa0, 0x4b,
	0x1e, 0xa1, 0x7d, 0x94, 0xee, 0xd8, 0x95, 0x65, 0x57, 0x6d, 0x05, 0x2f, 0x52, 0xd9, 0x4e, 0x82,
	0x21, 0x20, 0xb1, 0x1b, 0x9f, 0xfb, 0x3b, 0xc7, 0xbe, 0x33, 0xbe, 0x03, 0x05, 0x87, 0x62, 0xd7,
	0x63, 0x5c, 0x50, 0x9b, 0x57, 0x63, 0xeb, 0xca, 0xd0, 0x67, 0x82, 0xa1, 0x4c, 0x4c, 0xca, 0xaf,
	0xba, 0xcc, 0x65, 0xa1, 0x5e, 0x0d, 0x56, 0x11, 0x92, 0x2f, 0xba, 0x8c, 0xb9, 0x7d, 0x52, 0x0d,
	0x9f, 0x8e, 0x47, 0x27, 0x55, 0x41, 0x07, 0x84, 0x0b, 0x3c, 0x18, 0x46, 0xc0, 0x86, 0x0c, 0xb9,
	0x03, 0x22, 0x4c, 0x81, 0xc5, 0x88, 0x1b, 0xe4, 0xe3, 0x88, 0x70, 0xb1, 0x97, 0xfa, 0xfa, 0xad,
	0x98, 0xd8, 0xf8, 0x9e, 0x84, 0xff, 0x62, 0x25, 0x3e, 0x64, 0x1e, 0x27, 0x68, 0x17, 0xd2, 0x5c,
	0x60, 0x41, 0x64, 0xa9, 0x24, 0x95, 0x57, 0x76, 0x0a, 0x95, 0xf8, 0x67, 0xb5, 0x87, 0xc4, 0xc7,
	0x82, 0x32, 0x0f, 0xf7, 0x03, 0x1b, 0x31, 0x22, 0x16, 0xad, 0x42, 0xda, 0x27, 0xd8, 0x39, 0x93,
	0xe7, 0x4a, 0x52, 0x79, 0xd1, 0x88, 0x1e, 0xd0, 0x1e, 0x2c, 0x50, 0xcf, 0x21, 0x9f, 0x89, 0x2f,
	0x27, 0x4b, 0x52, 0x39, 0xb3, 0x93, 0xbf, 0x15, 0xa6, 0x47, 0xb5, 0xe8, 0xfd, 0xfb, 0xa9, 0x8b,
	0xdf, 0xc5, 0x84, 0x31, 0x31, 0x20, 0x15, 0x32, 0x61, 0xb4, 0xc5, 0xa9, 0x67, 0x13, 0x39, 0x35,
	0xf6, 0x47, 0xdd, 0x56, 0x26, 0xdd, 0x56, 0xba, 0x93, 0x6e, 0xf7, 0x53, 0xe7, 0x7f, 0x8a, 0x92,
	0x01, 0xa1, 0xc9, 0x0c, 0x3c, 0xe8, 0x10, 0xd6, 0xfa, 0x98, 0x0b, 0x8b, 0x8f, 0x6c, 0x9b, 0x70,
	0x7e, 0x32, 0xea, 0x5b, 0xfc, 0xcc, 0xb3, 0x2d, 0x2c, 0xe4, 0xf4, 0x23, 0xe3, 0x56, 0x83, 0x00,
	0x73, 0xea, 0x37, 0xcf, 0x3c, 0x5b, 0x15, 0xa8, 0x0e, 0xd9, 0x30, 0x98, 0xf8, 0x3e, 0xf3, 0x83,
	0xb8, 0xf9, 0x47, 0xc6, 0x65, 0x02, 0x9b, 0x16, 0xb8, 0x54, 0x81, 0x0a, 0x00, 0x37, 0x29, 0xf2,
	0x42, 0x49, 0x2a, 0x2f, 0x19, 0x4b, 0x53, 0x60, 0x7c, 0x46, 0x3f, 0x25, 0xc8, 0xde, 0xda, 0x27,
	0x54, 0x82, 0x0c, 0xf5, 0xa8, 0xa0, 0xb8, 0x4f, 0xbf, 0x10, 0x27, 0x3c, 0xa5, 0x45, 0x23, 0x2e,
	0xa1, 0xe7, 0xb0, 0x12, 0xed, 0xa2, 0x63, 0xf5, 0x08, 0x75, 0x7b, 0x22, 0x3c, 0x95, 0xa4, 0x91,
	0x1d, 0xab, 0x6f, 0x42, 0x31, 0xc0, 0xb0, 0x6f, 0xf7, 0xe8, 0x29, 0x99, 0x60, 0xc9, 0x08, 0x1b,
	0xab, 0x63, 0xec, 0x19, 0x64, 0x05, 0xf6, 0x5d, 0x22, 0x26, 0x54, 0x2a, 0xa4, 0x96, 0x23, 0xf1,
	0x06, 0xb2, 0x99, 0x77, 0x42, 0xfd, 0x01, 0x71, 0xac, 0x3e, 0x76, 0xc3, 0x0d, 0x4e, 0x1a, 0xcb,
	0x53, 0xb1, 0x89, 0xdd, 0xa8, 0xa3, 0xcd, 0x1f, 0x73, 0x90, 0xbb, 0xfb, 0x1b, 0xa1, 0xa7, 0x50,
	0x68, 0x77, 0x34, 0x43, 0xed, 0xea, 0xed, 0x96, 0xda, 0xb4, 0xcc, 0xae, 0xda, 0xd5, 0xac, 0x77,
	0x2d, 0xb3, 0xa3, 0xd5, 0xf4, 0x86, 0xae, 0xd5, 0x73, 0x09, 0xa4, 0x40, 0x7e, 0x16, 0x31, 0xbb,
	0xaa, 0xd1, 0xd5, 0x5b, 0x07, 0x39, 0x09, 0x95, 0x60, 0x7d, 0xb6, 0x5e, 0x6b, 0xb7, 0x5a, 0x5a,
	0x2d, 0x24, 0xe6, 0x50, 0x01, 0xfe, 0xbf, 0x27, 0xe1, 0xa8, 0x55, 0x0b, 0xca, 0x49, 0xb4, 0x09,
	0x2f, 0x66, 0xcb, 0x87, 0xaa, 0x1e, 0xb8, 0xad, 0x46, 0xdb, 0xb0, 0x1a, 0x7a, 0x4b, 0x6d, 0xea,
	0xdd, 0xa3, 0x5c, 0x0a, 0x3d, 0x81, 0xb5, 0x59, 0xd6, 0xd0, 0xd4, 0xfa, 0x51, 0x2e, 0x8d, 0x36,
	0x40, 0xb9, 0xaf, 0x18, 0xfb, 0x96, 0x79, 0xb4, 0x0e, 0xf2, 0x2c, 0xd3, 0x50, 0xf5, 0xa6, 0x56,
	0xcf, 0x2d, 0x3c, 0xd4, 0x6b, 0xbb, 0xd3, 0x09, 0xdc, 0x8b, 0x3b, 0x1f, 0x00, 0xd5, 0x6f, 0x06,
	0xc9, 0x24, 0xfe, 0x29, 0xb5, 0x09, 0x7a, 0x0b, 0x4b, 0xd3, 0x71, 0x46, 0xb7, 0xe7, 0xf6, 0xee,
	0x0d, 0x90, 0x57, 0x1e, 0x2a, 0x47, 0xb7, 0xc0, 0xfe, 0xe1, 0xc5, 0x95, 0x22, 0x5d, 0x5e, 0x29,
	0xd2, 0xdf, 0x2b, 0x45, 0x3a, 0xbf, 0x56, 0x12, 0x97, 0xd7, 0x4a, 0xe2, 0xd7, 0xb5, 0x92, 0x78,
	0xff, 0xda, 0xa5, 0xa2, 0x37, 0x3a, 0xae, 0xd8, 0x6c, 0x50, 0xf5, 0x98, 0x43, 0xb6, 0x5f, 0x6e,
	0x6f, 0x51, 0x56, 0x1d, 0xff, 0x34, 0x5b, 0x9f, 0x7c, 0x3c, 0x1c, 0x12, 0x3f, 0x7e, 0x99, 0xbd,
	0x8a, 0xad, 0x8f, 0xe7, 0xc3, 0xe1, 0xd8, 0xfd, 0x17, 0x00, 0x00, 0xff, 0xff, 0x31, 0xde, 0xd9,
	0x00, 0xfa, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DiagnosticsServiceClient is the client API for DiagnosticsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DiagnosticsServiceClient interface {
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error)
}

type diagnosticsServiceClient struct {
	cc grpc1.ClientConn
}

func NewDiagnosticsServiceClient(cc grpc1.ClientConn) DiagnosticsServiceClient {
	return &diagnosticsServiceClient{cc}
}

func (c *diagnosticsServiceClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, "/diagnostics.DiagnosticsService/GetStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DiagnosticsServiceServer is the server API for DiagnosticsService service.
type DiagnosticsServiceServer interface {
	GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error)
}

// UnimplementedDiagnosticsServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDiagnosticsServiceServer struct {
}

func (*UnimplementedDiagnosticsServiceServer) GetStatus(ctx context.Context, req *GetStatusRequest) (*GetStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}

func RegisterDiagnosticsServiceServer(s grpc1.Server, srv DiagnosticsServiceServer) {
	s.RegisterService(&_DiagnosticsService_serviceDesc, srv)
}

func _DiagnosticsService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiagnosticsServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/diagnostics.DiagnosticsService/GetStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiagnosticsServiceServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var DiagnosticsService_serviceDesc = _DiagnosticsService_serviceDesc
var _DiagnosticsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "diagnostics.DiagnosticsService",
	HandlerType: (*DiagnosticsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatus",
			Handler:    _DiagnosticsService_GetStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "diagnostics/diagnostics.proto",
}

func (m *GetStatusRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetStatusRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetStatusRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *GetStatusResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetStatusResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetStatusResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.LastError) > 0 {
		i -= len(m.LastError)
		copy(dAtA[i:], m.LastError)
		i = encodeVarintDiagnostics(dAtA, i, uint64(len(m.LastError)))
		i--
		dAtA[i] = 0x3a
	}
	if m.LastErrorAt != nil {
		n1, err1 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(*m.LastErrorAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.LastErrorAt):])
		if err1 != nil {
			return 0, err1
		}
		i -= n1
		i = encodeVarintDiagnostics(dAtA, i, uint64(n1))
		i--
		dAtA[i] = 0x32
	}
	if m.LastSuccessfulSyncAt != nil {
		n2, err2 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(*m.LastSuccessfulSyncAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.LastSuccessfulSyncAt):])
		if err2 != nil {
			return 0, err2
		}
		i -= n2
		i = encodeVarintDiagnostics(dAtA, i, uint64(n2))
		i--
		dAtA[i] = 0x2a
	}
	if m.StateSince != nil {
		n3, err3 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(*m.StateSince, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.StateSince):])
		if err3 != nil {
			return 0, err3
		}
		i -= n3
		i = encodeVarintDiagnostics(dAtA, i, uint64(n3))
		i--
		dAtA[i] = 0x22
	}
	{
		size, err := m.Indexer.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintDiagnostics(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if m.Ready {
		i--
		if m.Ready {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if m.State != 0 {
		i = encodeVarintDiagnostics(dAtA, i, uint64(m.State))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *IndexerStatus) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *IndexerStatus) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *IndexerStatus) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ConfirmedLag != 0 {
		i = encodeVarintDiagnostics(dAtA, i, uint64(m.ConfirmedLag))
		i--
		dAtA[i] = 0x28
	}
	if m.TargetHeight != 0 {
		i = encodeVarintDiagnostics(dAtA, i, uint64(m.TargetHeight))
		i--
		dAtA[i] = 0x20
	}
	if m.ArchiveHeight != 0 {
		i = encodeVarintDiagnostics(dAtA, i, uint64(m.ArchiveHeight))
		i--
		dAtA[i] = 0x18
	}
	if m.IndexedHeight != 0 {
		i = encodeVarintDiagnostics(dAtA, i, uint64(m.IndexedHeight))
		i--
		dAtA[i] = 0x10
	}
	if m.Initialized {
		i--
		if m.Initialized {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintDiagnostics(dAtA []byte, offset int, v uint64) int {
	offset -= sovDiagnostics(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GetStatusRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *GetStatusResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.State != 0 {
		n += 1 + sovDiagnostics(uint64(m.State))
	}
	if m.Ready {
		n += 2
	}
	l = m.Indexer.Size()
	n += 1 + l + sovDiagnostics(uint64(l))
	if m.StateSince != nil {
		l = github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.StateSince)
		n += 1 + l + sovDiagnostics(uint64(l))
	}
	if m.LastSuccessfulSyncAt != nil {
		l = github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.LastSuccessfulSyncAt)
		n += 1 + l + sovDiagnostics(uint64(l))
	}
	if m.LastErrorAt != nil {
		l = github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.LastErrorAt)
		n += 1 + l + sovDiagnostics(uint64(l))
	}
	l = len(m.LastError)
	if l > 0 {
		n += 1 + l + sovDiagnostics(uint64(l))
	}
	return n
}

func (m *IndexerStatus) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Initialized {
		n += 2
	}
	if m.IndexedHeight != 0 {
		n += 1 + sovDiagnostics(uint64(m.IndexedHeight))
	}
	if m.ArchiveHeight != 0 {
		n += 1 + sovDiagnostics(uint64(m.ArchiveHeight))
	}
	if m.TargetHeight != 0 {
		n += 1 + sovDiagnostics(uint64(m.TargetHeight))
	}
	if m.ConfirmedLag != 0 {
		n += 1 + sovDiagnostics(uint64(m.ConfirmedLag))
	}
	return n
}

func sovDiagnostics(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozDiagnostics(x uint64) (n int) {
	return sovDiagnostics(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GetStatusRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDiagnostics
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetStatusRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetStatusRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipDiagnostics(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDiagnostics
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetStatusResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDiagnostics
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetStatusResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetStatusResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field State", wireType)
			}
			m.State = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDiagnostics
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.State |= OperationalState(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ready", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDiagnostics
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Ready = bool(v != 0)
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Indexer", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDiagnostics
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDiagnostics
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDiagnostics
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Indexer.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StateSince", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDiagnostics
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDiagnostics
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDiagnostics
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.StateSince == nil {
				m.StateSince = new(time.Time)
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(m.StateSince, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastSuccessfulSyncAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDiagnostics
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDiagnostics
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDiagnostics
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.LastSuccessfulSyncAt == nil {
				m.LastSuccessfulSyncAt = new(time.Time)
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(m.LastSuccessfulSyncAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastErrorAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDiagnostics
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDiagnostics
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDiagnostics
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.LastErrorAt == nil {
				m.LastErrorAt = new(time.Time)
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(m.LastErrorAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastError", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDiagnostics
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDiagnostics
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDiagnostics
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LastError = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDiagnostics(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDiagnostics
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *IndexerStatus) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDiagnostics
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: IndexerStatus: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: IndexerStatus: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Initialized", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDiagnostics
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Initialized = bool(v != 0)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IndexedHeight", wireType)
			}
			m.IndexedHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDiagnostics
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.IndexedHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ArchiveHeight", wireType)
			}
			m.ArchiveHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDiagnostics
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ArchiveHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TargetHeight", wireType)
			}
			m.TargetHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDiagnostics
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TargetHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConfirmedLag", wireType)
			}
			m.ConfirmedLag = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDiagnostics
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ConfirmedLag |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipDiagnostics(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDiagnostics
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipDiagnostics(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowDiagnostics
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDiagnostics
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDiagnostics
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthDiagnostics
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupDiagnostics
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthDiagnostics
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthDiagnostics        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowDiagnostics          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupDiagnostics = fmt.Errorf("proto: unexpected end of group")
)
